// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shows.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getShow = `-- name: GetShow :one
SELECT id, venue_id, promoter_id, title, doors_open, starts_at, ends_at, status, prices, cancellation_reason, version
FROM show.shows WHERE id = $1
`

type GetShowRow struct {
	ID                 uuid.UUID
	VenueID            uuid.UUID
	PromoterID         uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
	Version            int32
}

func (q *Queries) GetShow(ctx context.Context, id uuid.UUID) (GetShowRow, error) {
	row := q.db.QueryRow(ctx, getShow, id)
	var i GetShowRow
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.PromoterID,
		&i.Title,
		&i.DoorsOpen,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.Prices,
		&i.CancellationReason,
		&i.Version,
	)
	return i, err
}

const insertShow = `-- name: InsertShow :execrows
INSERT INTO show.shows (id, venue_id, promoter_id, title, doors_open, starts_at, ends_at, status, prices, cancellation_reason, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 1)
ON CONFLICT (id) DO NOTHING
`

type InsertShowParams struct {
	ID                 uuid.UUID
	VenueID            uuid.UUID
	PromoterID         uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
}

func (q *Queries) InsertShow(ctx context.Context, arg InsertShowParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertShow,
		arg.ID,
		arg.VenueID,
		arg.PromoterID,
		arg.Title,
		arg.DoorsOpen,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.Prices,
		arg.CancellationReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEndedShows = `-- name: ListEndedShows :many
SELECT id FROM show.shows WHERE status IN ('published', 'sold_out') AND ends_at <= $1
`

func (q *Queries) ListEndedShows(ctx context.Context, endsAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEndedShows, endsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenShowsAtVenue = `-- name: ListOpenShowsAtVenue :many
SELECT id, venue_id, promoter_id, title, doors_open, starts_at, ends_at, status, prices, cancellation_reason, version
FROM show.shows
WHERE venue_id = $1 AND status NOT IN ('cancelled', 'completed')
ORDER BY starts_at
`

type ListOpenShowsAtVenueRow struct {
	ID                 uuid.UUID
	VenueID            uuid.UUID
	PromoterID         uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
	Version            int32
}

func (q *Queries) ListOpenShowsAtVenue(ctx context.Context, venueID uuid.UUID) ([]ListOpenShowsAtVenueRow, error) {
	rows, err := q.db.Query(ctx, listOpenShowsAtVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenShowsAtVenueRow
	for rows.Next() {
		var i ListOpenShowsAtVenueRow
		if err := rows.Scan(
			&i.ID,
			&i.VenueID,
			&i.PromoterID,
			&i.Title,
			&i.DoorsOpen,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.Prices,
			&i.CancellationReason,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShow = `-- name: UpdateShow :execrows
UPDATE show.shows
SET title = $2, doors_open = $3, starts_at = $4, ends_at = $5, status = $6, prices = $7,
    cancellation_reason = $8, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $9
`

type UpdateShowParams struct {
	ID                 uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
	ExpectedVersion    int32
}

func (q *Queries) UpdateShow(ctx context.Context, arg UpdateShowParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateShow,
		arg.ID,
		arg.Title,
		arg.DoorsOpen,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.Prices,
		arg.CancellationReason,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
