// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venue_layouts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getVenueLayout = `-- name: GetVenueLayout :one
SELECT venue_id, name, active, sections FROM show.venue_layouts WHERE venue_id = $1
`

type GetVenueLayoutRow struct {
	VenueID  uuid.UUID
	Name     string
	Active   bool
	Sections []byte
}

func (q *Queries) GetVenueLayout(ctx context.Context, venueID uuid.UUID) (GetVenueLayoutRow, error) {
	row := q.db.QueryRow(ctx, getVenueLayout, venueID)
	var i GetVenueLayoutRow
	err := row.Scan(
		&i.VenueID,
		&i.Name,
		&i.Active,
		&i.Sections,
	)
	return i, err
}

const upsertVenueLayout = `-- name: UpsertVenueLayout :exec
INSERT INTO show.venue_layouts (venue_id, name, active, sections)
VALUES ($1, $2, $3, $4)
ON CONFLICT (venue_id) DO UPDATE
SET name = EXCLUDED.name, active = EXCLUDED.active, sections = EXCLUDED.sections, updated_at = now()
`

type UpsertVenueLayoutParams struct {
	VenueID  uuid.UUID
	Name     string
	Active   bool
	Sections []byte
}

func (q *Queries) UpsertVenueLayout(ctx context.Context, arg UpsertVenueLayoutParams) error {
	_, err := q.db.Exec(ctx, upsertVenueLayout,
		arg.VenueID,
		arg.Name,
		arg.Active,
		arg.Sections,
	)
	return err
}
