// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ShowOutbox struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	MsgKey      string
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
	PublishedAt pgtype.Timestamptz
}

type ShowShow struct {
	ID                 uuid.UUID
	VenueID            uuid.UUID
	PromoterID         uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ShowVenueLayout struct {
	VenueID   uuid.UUID
	Name      string
	Active    bool
	Sections  []byte
	UpdatedAt time.Time
}

type TicketingHold struct {
	HoldID     uuid.UUID
	ShowID     uuid.UUID
	CustomerID uuid.UUID
	Seats      []string
	ExpiresAt  time.Time
}

type TicketingInventory struct {
	ShowID    uuid.UUID
	StartsAt  time.Time
	Closed    bool
	SoldOut   bool
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TicketingOutbox struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	MsgKey      string
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
	PublishedAt pgtype.Timestamptz
}

type TicketingSeat struct {
	ShowID      uuid.UUID
	SeatRef     string
	Position    int32
	PriceAmount int64
	Currency    string
	State       string
	HoldID      pgtype.UUID
	OrderID     pgtype.UUID
}

type VenueOutbox struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	MsgKey      string
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
	PublishedAt pgtype.Timestamptz
}

type VenueSection struct {
	VenueID  uuid.UUID
	Code     string
	Position int32
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

type VenueVenue struct {
	ID        uuid.UUID
	Name      string
	Street    string
	City      string
	Country   string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
