// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
)

type VenueSection struct {
	VenueID  uuid.UUID
	Code     string
	Position int32
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

type VenueVenue struct {
	ID        uuid.UUID
	Name      string
	Street    string
	City      string
	Country   string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
