// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type VenueOutbox struct {
	ID          int64
	EventID     uuid.UUID
	Topic       string
	MsgKey      string
	EventType   string
	Payload     []byte
	OccurredAt  time.Time
	PublishedAt pgtype.Timestamptz
}

type VenueSection struct {
	VenueID  uuid.UUID
	Code     string
	Position int32
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

type VenueVenue struct {
	ID        uuid.UUID
	Name      string
	Street    string
	City      string
	Country   string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
