// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: venues.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteSections = `-- name: DeleteSections :exec
DELETE FROM venue.sections WHERE venue_id = $1
`

func (q *Queries) DeleteSections(ctx context.Context, venueID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSections, venueID)
	return err
}

const getVenue = `-- name: GetVenue :one
SELECT id, name, street, city, country, status, version
FROM venue.venues
WHERE id = $1
`

type GetVenueRow struct {
	ID      uuid.UUID
	Name    string
	Street  string
	City    string
	Country string
	Status  string
	Version int32
}

func (q *Queries) GetVenue(ctx context.Context, id uuid.UUID) (GetVenueRow, error) {
	row := q.db.QueryRow(ctx, getVenue, id)
	var i GetVenueRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const insertSection = `-- name: InsertSection :exec
INSERT INTO venue.sections (venue_id, code, position, name, kind, capacity, rows)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSectionParams struct {
	VenueID  uuid.UUID
	Code     string
	Position int32
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

func (q *Queries) InsertSection(ctx context.Context, arg InsertSectionParams) error {
	_, err := q.db.Exec(ctx, insertSection,
		arg.VenueID,
		arg.Code,
		arg.Position,
		arg.Name,
		arg.Kind,
		arg.Capacity,
		arg.Rows,
	)
	return err
}

const insertVenue = `-- name: InsertVenue :execrows
INSERT INTO venue.venues (id, name, street, city, country, status, version)
VALUES ($1, $2, $3, $4, $5, $6, 1)
ON CONFLICT (id) DO NOTHING
`

type InsertVenueParams struct {
	ID      uuid.UUID
	Name    string
	Street  string
	City    string
	Country string
	Status  string
}

// A second registration of the same id inserts nothing: 0 rows ⇒ conflict.
func (q *Queries) InsertVenue(ctx context.Context, arg InsertVenueParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertVenue,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Country,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSections = `-- name: ListSections :many
SELECT code, name, kind, capacity, rows
FROM venue.sections
WHERE venue_id = $1
ORDER BY position
`

type ListSectionsRow struct {
	Code     string
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

func (q *Queries) ListSections(ctx context.Context, venueID uuid.UUID) ([]ListSectionsRow, error) {
	rows, err := q.db.Query(ctx, listSections, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionsRow
	for rows.Next() {
		var i ListSectionsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Capacity,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :execrows
UPDATE venue.venues
SET name = $2, street = $3, city = $4, country = $5, status = $6,
    version = version + 1, updated_at = now()
WHERE id = $1 AND version = $7
`

type UpdateVenueParams struct {
	ID              uuid.UUID
	Name            string
	Street          string
	City            string
	Country         string
	Status          string
	ExpectedVersion int32
}

// 0 rows ⇒ someone else saved first ⇒ ErrConcurrentModification (ADR-011).
func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVenue,
		arg.ID,
		arg.Name,
		arg.Street,
		arg.City,
		arg.Country,
		arg.Status,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
