// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getVenueView = `-- name: GetVenueView :one

SELECT v.id, v.name, v.street, v.city, v.country, v.status,
       COALESCE(SUM(s.capacity), 0)::int AS capacity
FROM venue.venues v
LEFT JOIN venue.sections s ON s.venue_id = v.id
WHERE v.id = $1
GROUP BY v.id
`

type GetVenueViewRow struct {
	ID       uuid.UUID
	Name     string
	Street   string
	City     string
	Country  string
	Status   string
	Capacity int32
}

// The read side: flat views straight from SQL, never through the aggregate.
func (q *Queries) GetVenueView(ctx context.Context, id uuid.UUID) (GetVenueViewRow, error) {
	row := q.db.QueryRow(ctx, getVenueView, id)
	var i GetVenueViewRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Street,
		&i.City,
		&i.Country,
		&i.Status,
		&i.Capacity,
	)
	return i, err
}

const listSectionsOfVenues = `-- name: ListSectionsOfVenues :many
SELECT venue_id, code, name, kind, capacity, rows
FROM venue.sections
WHERE venue_id = ANY($1::uuid[])
ORDER BY venue_id, position
`

type ListSectionsOfVenuesRow struct {
	VenueID  uuid.UUID
	Code     string
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

func (q *Queries) ListSectionsOfVenues(ctx context.Context, venueIds []uuid.UUID) ([]ListSectionsOfVenuesRow, error) {
	rows, err := q.db.Query(ctx, listSectionsOfVenues, venueIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionsOfVenuesRow
	for rows.Next() {
		var i ListSectionsOfVenuesRow
		if err := rows.Scan(
			&i.VenueID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Capacity,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueViewsByStatus = `-- name: ListVenueViewsByStatus :many
SELECT v.id, v.name, v.street, v.city, v.country, v.status,
       COALESCE(SUM(s.capacity), 0)::int AS capacity
FROM venue.venues v
LEFT JOIN venue.sections s ON s.venue_id = v.id
WHERE v.status = $1
GROUP BY v.id
ORDER BY v.name, v.id
`

type ListVenueViewsByStatusRow struct {
	ID       uuid.UUID
	Name     string
	Street   string
	City     string
	Country  string
	Status   string
	Capacity int32
}

func (q *Queries) ListVenueViewsByStatus(ctx context.Context, status string) ([]ListVenueViewsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listVenueViewsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueViewsByStatusRow
	for rows.Next() {
		var i ListVenueViewsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Street,
			&i.City,
			&i.Country,
			&i.Status,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
