// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getCheckoutProcess = `-- name: GetCheckoutProcess :one
SELECT order_id, show_id, state, version FROM ticketing.checkout_processes WHERE order_id = $1
`

type GetCheckoutProcessRow struct {
	OrderID uuid.UUID
	ShowID  uuid.UUID
	State   string
	Version int32
}

func (q *Queries) GetCheckoutProcess(ctx context.Context, orderID uuid.UUID) (GetCheckoutProcessRow, error) {
	row := q.db.QueryRow(ctx, getCheckoutProcess, orderID)
	var i GetCheckoutProcessRow
	err := row.Scan(
		&i.OrderID,
		&i.ShowID,
		&i.State,
		&i.Version,
	)
	return i, err
}

const insertCheckoutProcess = `-- name: InsertCheckoutProcess :execrows
INSERT INTO ticketing.checkout_processes (order_id, show_id, state, version) VALUES ($1, $2, $3, 1)
ON CONFLICT (order_id) DO NOTHING
`

type InsertCheckoutProcessParams struct {
	OrderID uuid.UUID
	ShowID  uuid.UUID
	State   string
}

func (q *Queries) InsertCheckoutProcess(ctx context.Context, arg InsertCheckoutProcessParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCheckoutProcess, arg.OrderID, arg.ShowID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCheckoutProcess = `-- name: UpdateCheckoutProcess :execrows
UPDATE ticketing.checkout_processes SET state = $2, version = version + 1, updated_at = now()
WHERE order_id = $1 AND version = $3
`

type UpdateCheckoutProcessParams struct {
	OrderID         uuid.UUID
	State           string
	ExpectedVersion int32
}

func (q *Queries) UpdateCheckoutProcess(ctx context.Context, arg UpdateCheckoutProcessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCheckoutProcess, arg.OrderID, arg.State, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
