// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForInsertSeats implements pgx.CopyFromSource.
type iteratorForInsertSeats struct {
	rows                 []InsertSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ShowID,
		r.rows[0].Section,
		r.rows[0].SeatRef,
		r.rows[0].Position,
		r.rows[0].PriceAmount,
		r.rows[0].Currency,
		r.rows[0].State,
		r.rows[0].HoldID,
		r.rows[0].OrderID,
	}, nil
}

func (r iteratorForInsertSeats) Err() error {
	return nil
}

func (q *Queries) InsertSeats(ctx context.Context, arg []InsertSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ticketing", "seats"}, []string{"show_id", "section", "seat_ref", "position", "price_amount", "currency", "state", "hold_id", "order_id"}, &iteratorForInsertSeats{rows: arg})
}
