// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteHolds = `-- name: DeleteHolds :exec
DELETE FROM ticketing.holds WHERE show_id = $1
`

func (q *Queries) DeleteHolds(ctx context.Context, showID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHolds, showID)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT show_id, starts_at, closed, sold_out, version FROM ticketing.inventories WHERE show_id = $1
`

type GetInventoryRow struct {
	ShowID   uuid.UUID
	StartsAt time.Time
	Closed   bool
	SoldOut  bool
	Version  int32
}

func (q *Queries) GetInventory(ctx context.Context, showID uuid.UUID) (GetInventoryRow, error) {
	row := q.db.QueryRow(ctx, getInventory, showID)
	var i GetInventoryRow
	err := row.Scan(
		&i.ShowID,
		&i.StartsAt,
		&i.Closed,
		&i.SoldOut,
		&i.Version,
	)
	return i, err
}

const getShowIDByHold = `-- name: GetShowIDByHold :one
SELECT show_id FROM ticketing.holds WHERE hold_id = $1
`

func (q *Queries) GetShowIDByHold(ctx context.Context, holdID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getShowIDByHold, holdID)
	var show_id uuid.UUID
	err := row.Scan(&show_id)
	return show_id, err
}

const insertHold = `-- name: InsertHold :exec
INSERT INTO ticketing.holds (hold_id, show_id, customer_id, seats, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertHoldParams struct {
	HoldID     uuid.UUID
	ShowID     uuid.UUID
	CustomerID uuid.UUID
	Seats      []string
	ExpiresAt  time.Time
}

func (q *Queries) InsertHold(ctx context.Context, arg InsertHoldParams) error {
	_, err := q.db.Exec(ctx, insertHold,
		arg.HoldID,
		arg.ShowID,
		arg.CustomerID,
		arg.Seats,
		arg.ExpiresAt,
	)
	return err
}

const insertInventory = `-- name: InsertInventory :execrows
INSERT INTO ticketing.inventories (show_id, starts_at, closed, sold_out, version)
VALUES ($1, $2, $3, $4, 1)
ON CONFLICT (show_id) DO NOTHING
`

type InsertInventoryParams struct {
	ShowID   uuid.UUID
	StartsAt time.Time
	Closed   bool
	SoldOut  bool
}

func (q *Queries) InsertInventory(ctx context.Context, arg InsertInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInventory,
		arg.ShowID,
		arg.StartsAt,
		arg.Closed,
		arg.SoldOut,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertSeatsParams struct {
	ShowID      uuid.UUID
	SeatRef     string
	Position    int32
	PriceAmount int64
	Currency    string
	State       string
	HoldID      uuid.NullUUID
	OrderID     uuid.NullUUID
}

const inventoryExists = `-- name: InventoryExists :one
SELECT EXISTS (SELECT 1 FROM ticketing.inventories WHERE show_id = $1)
`

// The read side: seats straight from the table.
func (q *Queries) InventoryExists(ctx context.Context, showID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, inventoryExists, showID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listHolds = `-- name: ListHolds :many
SELECT hold_id, customer_id, seats, expires_at FROM ticketing.holds WHERE show_id = $1
`

type ListHoldsRow struct {
	HoldID     uuid.UUID
	CustomerID uuid.UUID
	Seats      []string
	ExpiresAt  time.Time
}

func (q *Queries) ListHolds(ctx context.Context, showID uuid.UUID) ([]ListHoldsRow, error) {
	rows, err := q.db.Query(ctx, listHolds, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHoldsRow
	for rows.Next() {
		var i ListHoldsRow
		if err := rows.Scan(
			&i.HoldID,
			&i.CustomerID,
			&i.Seats,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeats = `-- name: ListSeats :many
SELECT seat_ref, price_amount, currency, state, hold_id, order_id
FROM ticketing.seats WHERE show_id = $1 ORDER BY position
`

type ListSeatsRow struct {
	SeatRef     string
	PriceAmount int64
	Currency    string
	State       string
	HoldID      uuid.NullUUID
	OrderID     uuid.NullUUID
}

func (q *Queries) ListSeats(ctx context.Context, showID uuid.UUID) ([]ListSeatsRow, error) {
	rows, err := q.db.Query(ctx, listSeats, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsRow
	for rows.Next() {
		var i ListSeatsRow
		if err := rows.Scan(
			&i.SeatRef,
			&i.PriceAmount,
			&i.Currency,
			&i.State,
			&i.HoldID,
			&i.OrderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const showsWithExpiredHolds = `-- name: ShowsWithExpiredHolds :many
SELECT DISTINCT show_id FROM ticketing.holds WHERE expires_at <= $1
`

func (q *Queries) ShowsWithExpiredHolds(ctx context.Context, expiresAt time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, showsWithExpiredHolds, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var show_id uuid.UUID
		if err := rows.Scan(&show_id); err != nil {
			return nil, err
		}
		items = append(items, show_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :execrows
UPDATE ticketing.inventories
SET closed = $2, sold_out = $3, version = version + 1, updated_at = now()
WHERE show_id = $1 AND version = $4
`

type UpdateInventoryParams struct {
	ShowID          uuid.UUID
	Closed          bool
	SoldOut         bool
	ExpectedVersion int32
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInventory,
		arg.ShowID,
		arg.Closed,
		arg.SoldOut,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSeat = `-- name: UpdateSeat :exec
UPDATE ticketing.seats SET state = $3, hold_id = $4, order_id = $5
WHERE show_id = $1 AND seat_ref = $2
`

type UpdateSeatParams struct {
	ShowID  uuid.UUID
	SeatRef string
	State   string
	HoldID  uuid.NullUUID
	OrderID uuid.NullUUID
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) error {
	_, err := q.db.Exec(ctx, updateSeat,
		arg.ShowID,
		arg.SeatRef,
		arg.State,
		arg.HoldID,
		arg.OrderID,
	)
	return err
}
