// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationsInbox struct {
	Consumer    string
	EventID     string
	ProcessedAt time.Time
}

type ShowOutbox struct {
	ID            int64
	EventID       uuid.UUID
	Topic         string
	MsgKey        string
	EventType     string
	Payload       []byte
	OccurredAt    time.Time
	PublishedAt   pgtype.Timestamptz
	CorrelationID string
	CausationID   string
}

type ShowShow struct {
	ID                 uuid.UUID
	VenueID            uuid.UUID
	PromoterID         uuid.UUID
	Title              string
	DoorsOpen          time.Time
	StartsAt           time.Time
	EndsAt             time.Time
	Status             string
	Prices             []byte
	CancellationReason string
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ShowVenueLayout struct {
	VenueID   uuid.UUID
	Name      string
	Active    bool
	Sections  []byte
	UpdatedAt time.Time
}

type TicketingHold struct {
	HoldID     uuid.UUID
	ShowID     uuid.UUID
	CustomerID uuid.UUID
	Seats      []string
	ExpiresAt  time.Time
	Section    string
}

type TicketingOrder struct {
	ID           uuid.UUID
	ShowID       uuid.UUID
	HoldID       uuid.UUID
	CustomerID   uuid.UUID
	ContactEmail string
	Lines        []byte
	TotalAmount  int64
	Currency     string
	Status       string
	PaymentRef   string
	Version      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TicketingOutbox struct {
	ID            int64
	EventID       uuid.UUID
	Topic         string
	MsgKey        string
	EventType     string
	Payload       []byte
	OccurredAt    time.Time
	PublishedAt   pgtype.Timestamptz
	CorrelationID string
	CausationID   string
}

type TicketingSeat struct {
	ShowID      uuid.UUID
	SeatRef     string
	Position    int32
	PriceAmount int64
	Currency    string
	State       string
	HoldID      uuid.NullUUID
	OrderID     uuid.NullUUID
	Section     string
}

type TicketingSectionInventory struct {
	ShowID    uuid.UUID
	Section   string
	Position  int32
	StartsAt  time.Time
	Closed    bool
	SoldOut   bool
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TicketingTicket struct {
	ID          uuid.UUID
	Code        string
	ShowID      uuid.UUID
	OrderID     uuid.UUID
	SeatRef     string
	Status      string
	Version     int32
	CheckedInAt pgtype.Timestamptz
	Gate        string
}

type VenueOutbox struct {
	ID            int64
	EventID       uuid.UUID
	Topic         string
	MsgKey        string
	EventType     string
	Payload       []byte
	OccurredAt    time.Time
	PublishedAt   pgtype.Timestamptz
	CorrelationID string
	CausationID   string
}

type VenueSection struct {
	VenueID  uuid.UUID
	Code     string
	Position int32
	Name     string
	Kind     string
	Capacity int32
	Rows     []byte
}

type VenueVenue struct {
	ID        uuid.UUID
	Name      string
	Street    string
	City      string
	Country   string
	Status    string
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
