// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrder = `-- name: GetOrder :one
SELECT id, show_id, hold_id, customer_id, contact_email, lines, total_amount, currency, status, payment_ref, version, subtotal_amount, fee_amount, vat_amount
FROM ticketing.orders WHERE id = $1
`

type GetOrderRow struct {
	ID             uuid.UUID
	ShowID         uuid.UUID
	HoldID         uuid.UUID
	CustomerID     uuid.UUID
	ContactEmail   string
	Lines          []byte
	TotalAmount    int64
	Currency       string
	Status         string
	PaymentRef     string
	Version        int32
	SubtotalAmount int64
	FeeAmount      int64
	VatAmount      int64
}

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.ShowID,
		&i.HoldID,
		&i.CustomerID,
		&i.ContactEmail,
		&i.Lines,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.PaymentRef,
		&i.Version,
		&i.SubtotalAmount,
		&i.FeeAmount,
		&i.VatAmount,
	)
	return i, err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT id, code, show_id, order_id, seat_ref, status, version, checked_in_at, gate FROM ticketing.tickets WHERE code = $1
`

func (q *Queries) GetTicketByCode(ctx context.Context, code string) (TicketingTicket, error) {
	row := q.db.QueryRow(ctx, getTicketByCode, code)
	var i TicketingTicket
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ShowID,
		&i.OrderID,
		&i.SeatRef,
		&i.Status,
		&i.Version,
		&i.CheckedInAt,
		&i.Gate,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :execrows
INSERT INTO ticketing.orders (id, show_id, hold_id, customer_id, contact_email, lines, total_amount, currency, status, payment_ref, version,
                              subtotal_amount, fee_amount, vat_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 1, $11, $12, $13)
ON CONFLICT (id) DO NOTHING
`

type InsertOrderParams struct {
	ID             uuid.UUID
	ShowID         uuid.UUID
	HoldID         uuid.UUID
	CustomerID     uuid.UUID
	ContactEmail   string
	Lines          []byte
	TotalAmount    int64
	Currency       string
	Status         string
	PaymentRef     string
	SubtotalAmount int64
	FeeAmount      int64
	VatAmount      int64
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.ShowID,
		arg.HoldID,
		arg.CustomerID,
		arg.ContactEmail,
		arg.Lines,
		arg.TotalAmount,
		arg.Currency,
		arg.Status,
		arg.PaymentRef,
		arg.SubtotalAmount,
		arg.FeeAmount,
		arg.VatAmount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTicket = `-- name: InsertTicket :exec
INSERT INTO ticketing.tickets (id, code, show_id, order_id, seat_ref, status, version)
VALUES ($1, $2, $3, $4, $5, $6, 1)
ON CONFLICT (id) DO NOTHING
`

type InsertTicketParams struct {
	ID      uuid.UUID
	Code    string
	ShowID  uuid.UUID
	OrderID uuid.UUID
	SeatRef string
	Status  string
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) error {
	_, err := q.db.Exec(ctx, insertTicket,
		arg.ID,
		arg.Code,
		arg.ShowID,
		arg.OrderID,
		arg.SeatRef,
		arg.Status,
	)
	return err
}

const listPaidOrdersForShow = `-- name: ListPaidOrdersForShow :many
SELECT id, show_id, hold_id, customer_id, contact_email, lines, total_amount, currency, status, payment_ref, version, subtotal_amount, fee_amount, vat_amount
FROM ticketing.orders WHERE show_id = $1 AND status IN ('paid', 'fulfilled')
`

type ListPaidOrdersForShowRow struct {
	ID             uuid.UUID
	ShowID         uuid.UUID
	HoldID         uuid.UUID
	CustomerID     uuid.UUID
	ContactEmail   string
	Lines          []byte
	TotalAmount    int64
	Currency       string
	Status         string
	PaymentRef     string
	Version        int32
	SubtotalAmount int64
	FeeAmount      int64
	VatAmount      int64
}

func (q *Queries) ListPaidOrdersForShow(ctx context.Context, showID uuid.UUID) ([]ListPaidOrdersForShowRow, error) {
	rows, err := q.db.Query(ctx, listPaidOrdersForShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaidOrdersForShowRow
	for rows.Next() {
		var i ListPaidOrdersForShowRow
		if err := rows.Scan(
			&i.ID,
			&i.ShowID,
			&i.HoldID,
			&i.CustomerID,
			&i.ContactEmail,
			&i.Lines,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.PaymentRef,
			&i.Version,
			&i.SubtotalAmount,
			&i.FeeAmount,
			&i.VatAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOrder = `-- name: ListTicketsByOrder :many
SELECT id, code, show_id, order_id, seat_ref, status, version, checked_in_at, gate FROM ticketing.tickets WHERE order_id = $1 ORDER BY seat_ref
`

func (q *Queries) ListTicketsByOrder(ctx context.Context, orderID uuid.UUID) ([]TicketingTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketingTicket
	for rows.Next() {
		var i TicketingTicket
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ShowID,
			&i.OrderID,
			&i.SeatRef,
			&i.Status,
			&i.Version,
			&i.CheckedInAt,
			&i.Gate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByShow = `-- name: ListTicketsByShow :many
SELECT id, code, show_id, order_id, seat_ref, status, version, checked_in_at, gate FROM ticketing.tickets WHERE show_id = $1 ORDER BY seat_ref
`

func (q *Queries) ListTicketsByShow(ctx context.Context, showID uuid.UUID) ([]TicketingTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByShow, showID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketingTicket
	for rows.Next() {
		var i TicketingTicket
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ShowID,
			&i.OrderID,
			&i.SeatRef,
			&i.Status,
			&i.Version,
			&i.CheckedInAt,
			&i.Gate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :execrows
UPDATE ticketing.orders SET status = $2, payment_ref = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $4
`

type UpdateOrderParams struct {
	ID              uuid.UUID
	Status          string
	PaymentRef      string
	ExpectedVersion int32
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrder,
		arg.ID,
		arg.Status,
		arg.PaymentRef,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTicket = `-- name: UpdateTicket :execrows
UPDATE ticketing.tickets SET status = $2, checked_in_at = $3, gate = $4, version = version + 1
WHERE id = $1 AND version = $5
`

type UpdateTicketParams struct {
	ID              uuid.UUID
	Status          string
	CheckedInAt     pgtype.Timestamptz
	Gate            string
	ExpectedVersion int32
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTicket,
		arg.ID,
		arg.Status,
		arg.CheckedInAt,
		arg.Gate,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
